#!/usr/bin/env node
const Templates = require('../lib/templates');
const CONSTANTS = require('../lib/utilities/constants');
const OPTIONS = require('../cli/options');
const path = require('path');

const PUBLIC_PATH = path.join(__dirname, '../public');
console.log('pub', PUBLIC_PATH);
const docsFile =
  process.env.NODE_ENV && process.env.NODE_ENV === 'production'
    ? 'docs'
    : 'docs-1';

const tps = new Templates('docs', {
  verbose: true,
  wipe: true
});

console.log(CONSTANTS.MAIN_DIR);

const data = {
  options: OPTIONS,
  wrapBrackets: text => {
    return `{{${text}}}`;
  },
  relPublic: dest => {
    return path.relative(path.dirname(dest), PUBLIC_PATH);
  }
};

tps
  .render(CONSTANTS.MAIN_DIR, docsFile, data)
  .then(() => {
    console.log('Docs generated');
  })
  .catch(e => {
    console.log('Error generating docs');
    console.log(e);
  });
