name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  #   test-debug:
  #     runs-on: ubuntu-latest
  #     strategy:
  #       matrix:
  #         node-version: [12.x]
  #     steps:
  #     - uses: actions/checkout@v1
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - name: Npm Install
  #       run: npm ci
  #       env:
  #         CI: true
  #     - name: Build Assests
  #       run: npm run code:build --if-present
  #     - name: Test Code
  #       run:  npm run test:core -- new/packages
  #       env:
  #         DEBUG: tps
  test-core:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install
        run: npm install
      - name: Build Assests
        run: npm run code:build
      - name: Test Code
        run: npm run test:core

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install
        run: npm install
      - name: Test Code
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Npm Install
        run: npm install
      - name: Test Code
        run: npm run typecheck
  # test-init:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [12.x, 10.x]
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #   - name: Npm Install
  #     run: npm install
  #     env:
  #       CI: true
  #   - name: Build Assests
  #     run: npm run code:build --if-present
  #   - name: Test Code
  #     run: sudo npm run test:init
